### ISSUE TITLE
logout need to be post and not get

### ISSUE THREAD

**Issue by ArroyaveInformatik** [CompuMasterGmbH/cammUtils-vTigerNetApi#13]
vTiger 6.5 and up need in order to logout an user a **request post** and not a **request get**, otherwise you will be stay logged in at background and obtaing following error message:
_{"success":false,"error":{"code":"OPERATION_NOT_SUPPORTED","message":"Permission to perform the operation is denied"}}_

Affected project: VTigerApi
Affected file: VTigerService.cs
Line: 334
Content of the error line: String.Format("sessionName={0}", sessionName), **false**);
Muste be corrected as follow: String.Format("sessionName={0}", sessionName), **true**);

**Comment by jochenwezel** [comment]
New NuGet package 2017.09.06.100 is now available
