### ISSUE TITLE
 INVALID_AUTH_TOKEN: Specified token is invalid or expired

### ISSUE THREAD

**Issue by Giancarlo67** [CompuMasterGmbH/cammUtils-vTigerNetApi#22]
Hi connecting to a vTiger version 6.2.0 works like a charm, but now trying to connect with a vTiger 7.3.0 installation gives the error "
INVALID_AUTH_TOKEN: Specified token is invalid or expired".
It's a brand new installation, it's the API key from the admin user, which is created along with the installation, so expired seems to be unlikely.

Found some other threads about this issue, but none which solves the issue for me.
Any hints to dig deeper in why this is happening?

**Comment by jochenwezel** [comment]
I tested successfully with the sample project and the live demo instance of vtiger 7.3 at https://simplesistemas.com/demo-de-vtiger-crm

So, there is no general issue with vtigerNetApi and vtiger 7.3.

**Comment by Giancarlo67** [comment]
Hi, you're update to  .NET framework v4.8 solved my issue too with the sample project.
However in my real project I still don't get loged in.
The reason is quite clear, somehow the user_name is blank, while it was available before.
I'm using the same method as the sample project to login:
            VTiger vtigerApi = new VTiger(txtDBServer.Text);
            vtigerApi.Login(txtDBUser.Text, txtDBPassword.Text);

The issue is visable in the debugging.
Everything works the same uptill this command: "SELECT id from vtiger_users where user_name=? AND deleted=0"
In the sample project the user_name is set as the parameter, but in my project the user_name parameter is empty.
Do you have a tip on where to look for this behaviour?

Sun Nov 15 11:05:28 2020,417 [26319] DEBUG webservice - Prepared sql query being executed : SELECT id from vtiger_users where user_name=? AND deleted=0
Sun Nov 15 11:05:28 2020,417 [26319] DEBUG webservice - Prepared sql query parameters : [admin]
Sun Nov 15 11:05:28 2020,417 [26319] DEBUG webservice - Prepared sql query being executed : delete from vtiger_ws_userauthtoken where userid=?
Sun Nov 15 11:05:28 2020,417 [26319] DEBUG webservice - Prepared sql query parameters : [1]
Sun Nov 15 11:05:28 2020,419 [26319] DEBUG webservice - Prepared sql query being executed : insert into vtiger_ws_userauthtoken(userid,token,expireTime) values (?,?,?)
Sun Nov 15 11:05:28 2020,419 [26319] DEBUG webservice - Prepared sql query parameters : [1,5fb10b7865e44,1605438628]
Sun Nov 15 11:05:29 2020,702 [25312] INFO VT - PearDatabase ->ADODB disconnect
Sun Nov 15 11:05:29 2020,722 [25312] DEBUG webservice - Prepared sql query being executed : select * from vtiger_ws_operation where name=?
Sun Nov 15 11:05:29 2020,722 [25312] DEBUG webservice - Prepared sql query parameters : [login]
Sun Nov 15 11:05:29 2020,723 [25312] DEBUG webservice - Prepared sql query being executed : select * from vtiger_ws_operation_parameters where operationid=? order by sequence
Sun Nov 15 11:05:29 2020,723 [25312] DEBUG webservice - Prepared sql query parameters : [1]
Sun Nov 15 11:05:29 2020,723 [25312] DEBUG user - Entering Users() method ...
Sun Nov 15 11:05:29 2020,723 [25312] DEBUG webservice - Entering getColumnFields(Users) method ...
Sun Nov 15 11:05:29 2020,723 [25312] DEBUG webservice - in getColumnFields Users
Sun Nov 15 11:05:29 2020,723 [25312] DEBUG webservice - Prepared sql query being executed : SELECT tabid, name, ownedby FROM vtiger_tab
Sun Nov 15 11:05:29 2020,724 [25312] DEBUG webservice - Prepared sql query being executed : SELECT tabid, fieldname, fieldid, fieldlabel, columnname, tablename, uitype, typeofdata, presence
		FROM vtiger_field WHERE tabid in (?)
Sun Nov 15 11:05:29 2020,724 [25312] DEBUG webservice - Prepared sql query parameters : [29]
Sun Nov 15 11:05:29 2020,725 [25312] DEBUG webservice - Exiting getColumnFields method ...
Sun Nov 15 11:05:29 2020,725 [25312] DEBUG user - Exiting Users() method ...
Sun Nov 15 11:05:29 2020,725 [25312] DEBUG webservice - Prepared sql query being executed : SELECT id from vtiger_users where user_name=? AND deleted=0
Sun Nov 15 11:05:29 2020,725 [25312] DEBUG webservice - Prepared sql query parameters : []
Sun Nov 15 11:05:29 2020,725 [25312] DEBUG webservice - Prepared sql query being executed : select token from vtiger_ws_userauthtoken where userid=? and expiretime >= ?
Sun Nov 15 11:05:29 2020,725 [25312] DEBUG webservice - Prepared sql query parameters : [,1605438329]

**Comment by jochenwezel** [comment]
Is the sample project working with your server environment and it's just your own project that doesn't work?

**Comment by jochenwezel** [comment]
In similar situations, I inspect the raw HTTP communication between client and server with the free tool https://www.telerik.com/fiddler 

Maybe you can also identify differences in the HTTP request series between the working set of client/server and your not working combination of your own client/server? Sometimes one of a previous responses provided a different result than expected, so you can at least identify the step when it starts going wrong.
![image](https://user-images.githubusercontent.com/3033827/99244136-f545c200-2801-11eb-92d9-ddf2d49bb0ec.png)

**Comment by Giancarlo67** [comment]
Hi Jochen,

Thank you for your support.
I fixed it by using www in front of the domainname.

**Comment by jochenwezel** [comment]
Thank you for your last feedback; I'm glad you solved it finally :-)
