### ISSUE TITLE
Trying to upload image to product

### ISSUE THREAD

**Issue by Giancarlo67** [CompuMasterGmbH/cammUtils-vTigerNetApi#24]
Hi We're trying to upload an image while creating or updating a product.

We made a new webservice for accepting the upload of the image.
When not actually adding the image ( "application/x-www-form-urlencoded") it runs fine, and make all the neccesarry entries in the database.

But when we actually change the contenttype from "application/x-www-form-urlencoded" to "multipart/form-data" we run into an issue.
This is the error message:  "AUTHENTICATION_REQUIRED".

This is the raw post:
POST https://www.mydomain.com/vtigercrm/webservice.php?operation=insert_attachment HTTP/1.1
Content-Type: multipart/form-data; boundary = -----------8d8a1466ac90462
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Host: www.mydomain.com
Content-Length: 25689
Expect: 100-continue

-------------8d8a1466ac90462
Content-Disposition: form-data; name="sessionName"

6ec11ae65fd9268f540fd
-------------8d8a1466ac90462
Content-Disposition: form-data; name="id"

14x31
-------------8d8a1466ac90462
Content-Disposition: form-data; name="module"

Products
-------------8d8a1466ac90462
Content-Disposition: form-data; name="imagename[]"; filename="image.jpg"
Content-Type: image/jpeg

   image data

This is a non production enviroment so if any testing is needed, it is no problem.
Any help would be appreciated.

**Comment by jochenwezel** [comment]
This question is related to the service interface of the vtiger server, not to this client library.
Maybe https://www.vtiger.com/docs/rest-api-for-vtiger#/Retrieve might also be a good starting point for research to this subject.
