### ISSUE TITLE
v2024.11.27.102: Project file is incomplete. Expected imports are missing.

### ISSUE THREAD

**Issue by Giancarlo67** [CompuMasterGmbH/cammUtils-vTigerNetApi#26]
We're trying to load the new version but cannot load the 4 projects, they all give this order:
Project file is incomplete. Expected imports are missing.

**Comment by jochenwezel** [comment]
Which project are you trying to open? The demo project or your own solution?
Where does the error occurs? In Visual Studio? On loading the solution? On building the solution?
Have you got a full error messag/log?

Screenshots often tell more than 1000 words ;-)

**Comment by Giancarlo67** [comment]
I've downloaded the zip of latest version (v2024.11.27.102) of your project and trying to load it in visual studio 2017.
B:\VS\cammUtils-vTigerNetApi-2024.11.27.102\VTigerApi\VTigerApi.csproj : error  : Project file is incomplete. Expected imports are missing.

B:\VS\cammUtils-vTigerNetApi-2024.11.27.102\VTigerManagerDemo\VTiger Manager Demo.csproj : error  : Project file is incomplete. Expected imports are missing.

B:\VS\cammUtils-vTigerNetApi-2024.11.27.102\VTigerManagerDemoControls\VTiger Manager Demo Tools.csproj : error  : Project file is incomplete. Expected imports are missing.

B:\VS\cammUtils-vTigerNetApi-2024.11.27.102\VTigerApiUnitTests\VTigerApiUnitTests.csproj : error  : Project file is incomplete. Expected imports are missing.

**Comment by jochenwezel** [comment]
Please use Visual Studio 2022 or higher and test again to load the project.

(If you just need the compiled DLL assembly, I recommend installing from NuGet at https://www.nuget.org/packages/VTigerNetApi )

**Comment by Giancarlo67** [comment]
When opened in Visual Studio 2022, the projects load, but there is this error:
Current solution contains incorrect configurations mappings. It may cause projects to not work correctly. Open the Configuration Manager to fix them. Open Configuration Manager

**Comment by jochenwezel** [comment]
In fact, I got the same warning when opening from extracted bin. I changed the selected platform from "Mixed Platform" to "Any CPU" and fully restartet Visual Studio. The warning disappeared.

Please note: it is just a warning, not an error. The solution build without errors at my computer. To start the solution, you have to set project "VTiger Manager Demo" as the start project.

The configured platforms for "Mixed Platform" and "x86" are not required. I removed these configurations in 7cf88ec3ab063c0d0ffdf9c20239a266b45bd37c and fixed a few thing in solution file, so the configuration issues should be resolved finally.
