### ISSUE TITLE
Testing with vTiger 8.3.0: Access denied errors

### ISSUE THREAD

**Issue by Giancarlo67** [CompuMasterGmbH/cammUtils-vTigerNetApi#27]
When running the test function in the Demo manager, these Typenames give the below error:
Account
Campaign
Contact
Email
Invoice
Lead
PBXManager
Potentials
PriceBook
Project
ProjectMilestone
ProjectTask
PurchaseOrder
Quote
SalesOrder
ServiceContract
Service
SMSNotifier

VTigerApi.VTigerApiException: ACCESS_DENIED: Permission to perform the operation is denied

   bij VTigerApi.VTiger.VTigerGetJson[T](String operation, String parameters, Boolean post) in B:\VS\cammUtils-vTigerNetApi-master\VTigerApi\VTigerService.cs:regel 737

   bij VTigerApi.VTiger.VTiger_Query[T](String query) in B:\VS\cammUtils-vTigerNetApi-master\VTigerApi\VTigerService.cs:regel 438

   bij VTigerApi.VTiger.Query(String query) in B:\VS\cammUtils-vTigerNetApi-master\VTigerApi\VTigerService.cs:regel 478

   bij VTigerManager.VTigerMan.ShowPage(Int32 pageNum) in B:\VS\cammUtils-vTigerNetApi-master\VTigerManagerDemo\VTigerMan.cs:regel 336

These typenames give no error:
Asset
Calendar
Document
Event
Faq
HelpDesk
ModComment
Product
Users
Vendor

And the Group typename give this errors:
System.Exception: Cannot import VTigerApi.VTigerResult`1[Jayrock.Json.JsonArray] from a JSON String value. (<br />
<b>Warning</b>:  Undefined array key "crmid" in <b>/home/xxx/public_html/xxx/include/Webservices/VtigerActorOperation.php</b> on line <b>325</b><br />
<br />
<b>Warning</b>:  Undefined array key "crmid" in <b>/home/xxx/public_html/xxx/include/Webservices/VtigerActorOperation.php</b> on line <b>325</b><br />
<br />
<b>Warning</b>:  Undefined array key "crmid" in <b>/home/xxx/public_html/xxx/include/Webservices/VtigerActorOperation.php</b> on line <b>325</b><br />
{"success":true,"result":[{"id":"20x2","groupname":"Team Selling","description":"Group Related to Sales"},{"id":"20x3","groupname":"Marketing Group","description":"Group Related to Marketing Activities"},{"id":"20x4","groupname":"Support Group","description":"Group Related to providing Support to Customers"}]})

   bij VTigerApi.VTiger.ImportJson[T](String json) in B:\VS\cammUtils-vTigerNetApi-master\VTigerApi\VTigerService.cs:regel 693

   bij VTigerApi.VTiger.VTigerGetJson[T](String operation, String parameters, Boolean post) in B:\VS\cammUtils-vTigerNetApi-master\VTigerApi\VTigerService.cs:regel 728

   bij VTigerApi.VTiger.VTiger_Query[T](String query) in B:\VS\cammUtils-vTigerNetApi-master\VTigerApi\VTigerService.cs:regel 438

   bij VTigerApi.VTiger.Query(String query) in B:\VS\cammUtils-vTigerNetApi-master\VTigerApi\VTigerService.cs:regel 478

   bij VTigerManager.VTigerMan.ShowPage(Int32 pageNum) in B:\VS\cammUtils-vTigerNetApi-master\VTigerManagerDemo\VTigerMan.cs:regel 336

**Comment by jochenwezel** [comment]
The vtiger backend seems to throw ACCESS_DENIED: Permission to perform the operation is denied
Fixes in backend might be required.

**Comment by Giancarlo67** [comment]
After some testing, I now found out that when you do a default installation (no additional modules installed) the products module isn't activated.
Once it gets activated, the access denied errors occur.
So now I can try to figure out what is changed with activating the products module.
It's not in the files, as I only delete the database tables for a "new" installation.

**Update:**
After the installation you get an installation result, which is replaced very fast, so you can't see the contents.
After that, there is a optional module selection screen.
If you close that screen, or replace the url to the index, all the optional modules seem to be activated.
Also the Products module, and then there are no access denied errors at all!
So for now our issue is bypassed, and we can start the migration.
At a later point I will try to figure out whats the real reason for this.

**Comment by jochenwezel** [comment]
Thank you very mcuh for your valuable update! 
Great to hear that this issue is solved for now :-)
